### ISSUE TITLE
Subdirectory support

### ISSUE THREAD

**Issue by ohbe1jacobi** [meew0/namida#1]
I'm a current user of tsunami-udp and I'm wondering - does this re-implementation add subdirectory support?  I'd like to maintain the directory structure while also grabbing all files in the tree.

**Comment by meew0** [comment]
Not at the moment, but it seems like it would not be too hard to implement. I'll take a look at it soon.
In the meantime you could also write a bash script or something similar that lists the files using `namida dir` and then creates the target folders and does the retrievals one by one.

**Comment by meew0** [comment]
Should be done, you can use it like:

```
$ namida get --server 127.0.0.1 --tree a/b/c/d/e.txt
```

This will create the folder tree `a/b/c/d` in the current directory, and place the remote file `a/b/c/d/e.txt` in there.

**Comment by ohbe1jacobi** [comment]
@meew0 

If I run a server with `namida serve /home/example/documents`  which contains `example/example.txt` and `example2/example.txt` I would like to, on the client machine run `namida get --server example.com --all` and have it create both subdirectories `example` and `example2` and then place `example.txt` and `example2.txt` in the correct subdirectories.

Would that work with the current update?  If not, would that be a feature request you could support?

**Comment by ohbe1jacobi** [comment]
Nevermind, tested it myself and works as expected.  `namida get --server example.com --all --tree`
